name: react-rust-postgres
services:
  frontend:
    build:
      context: frontend
      # target: builder
      target: development
    container_name: frontend
    hostname: frontend
    working_dir: /code/src
    networks:
      - client-side
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - node-modules:/code/node_modules
      #- ./frontend/node_modules:/code/node_modules

  backend:
    build:
      context: backend
      target: development
    container_name: backend
    hostname: backend
    working_dir: /code/src
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug
      - PG_DBNAME=atacs2024_db
      - PG_HOST=db
      - PG_USER=sekiguchi
      - PG_PASSWORD=kaseki
    networks:
      - client-side
      - server-side
    volumes:
      - ./backend/src:/code/src
      - backend-cache:/code/target
    depends_on:
      - db

  db:
    build:
      context: db
      target: development
      #image: postgres:12-alpine
    restart: always
    container_name: pgdb
    hostname: pgdb
    working_dir: /root/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server-side
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/root/data
      - db-data:/var/lib/postgresql/data

networks:
  client-side: {}
  server-side: {}

volumes:
  backend-cache: {}
  db-data: {}
  node-modules: {}
